# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vipeg\Desktop\lol\create.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create_note(object):
    def setupUi(self, Create_note):
        Create_note.setObjectName("Create_note")
        Create_note.resize(491, 371)
        self.create_label = QtWidgets.QLabel(Create_note)
        self.create_label.setGeometry(QtCore.QRect(210, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.create_label.setFont(font)
        self.create_label.setObjectName("create_label")
        self.create_text = QtWidgets.QTextEdit(Create_note)
        self.create_text.setGeometry(QtCore.QRect(40, 190, 391, 101))
        self.create_text.setObjectName("create_text")
        self.create_doctor_first = QtWidgets.QLineEdit(Create_note)
        self.create_doctor_first.setGeometry(QtCore.QRect(40, 60, 171, 20))
        self.create_doctor_first.setText("")
        self.create_doctor_first.setReadOnly(True)
        self.create_doctor_first.setObjectName("create_doctor_first")
        self.create_pacient_first = QtWidgets.QLineEdit(Create_note)
        self.create_pacient_first.setGeometry(QtCore.QRect(40, 120, 171, 20))
        self.create_pacient_first.setText("")
        self.create_pacient_first.setReadOnly(False)
        self.create_pacient_first.setObjectName("create_pacient_first")
        self.create_label_2 = QtWidgets.QLabel(Create_note)
        self.create_label_2.setGeometry(QtCore.QRect(200, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.create_label_2.setFont(font)
        self.create_label_2.setObjectName("create_label_2")
        self.create_label_3 = QtWidgets.QLabel(Create_note)
        self.create_label_3.setGeometry(QtCore.QRect(170, 150, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.create_label_3.setFont(font)
        self.create_label_3.setObjectName("create_label_3")
        self.create_btn = QtWidgets.QPushButton(Create_note)
        self.create_btn.setGeometry(QtCore.QRect(190, 310, 75, 23))
        self.create_btn.setObjectName("create_btn")
        self.create_doctor_last = QtWidgets.QLineEdit(Create_note)
        self.create_doctor_last.setGeometry(QtCore.QRect(260, 60, 171, 20))
        self.create_doctor_last.setText("")
        self.create_doctor_last.setReadOnly(True)
        self.create_doctor_last.setObjectName("create_doctor_last")
        self.create_pacient_last = QtWidgets.QLineEdit(Create_note)
        self.create_pacient_last.setGeometry(QtCore.QRect(260, 120, 171, 20))
        self.create_pacient_last.setText("")
        self.create_pacient_last.setReadOnly(False)
        self.create_pacient_last.setObjectName("create_pacient_last")

        self.retranslateUi(Create_note)
        QtCore.QMetaObject.connectSlotsByName(Create_note)

    def retranslateUi(self, Create_note):
        _translate = QtCore.QCoreApplication.translate
        Create_note.setWindowTitle(_translate("Create_note", "Create note"))
        self.create_label.setText(_translate("Create_note", "Доктор"))
        self.create_doctor_first.setPlaceholderText(_translate("Create_note", "Имя"))
        self.create_pacient_first.setPlaceholderText(_translate("Create_note", "Имя"))
        self.create_label_2.setText(_translate("Create_note", "Пациент"))
        self.create_label_3.setText(_translate("Create_note", "Комментарий"))
        self.create_btn.setText(_translate("Create_note", "Создать"))
        self.create_doctor_last.setPlaceholderText(_translate("Create_note", "Фамилия"))
        self.create_pacient_last.setPlaceholderText(_translate("Create_note", "Фамилия"))
