# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vipeg\Desktop\lol\edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit_window(object):
    def setupUi(self, Edit_window):
        Edit_window.setObjectName("Edit_window")
        Edit_window.resize(321, 376)
        self.edit_doctor = QtWidgets.QLineEdit(Edit_window)
        self.edit_doctor.setGeometry(QtCore.QRect(50, 70, 221, 20))
        self.edit_doctor.setReadOnly(True)
        self.edit_doctor.setObjectName("edit_doctor")
        self.edit_pacient = QtWidgets.QLineEdit(Edit_window)
        self.edit_pacient.setGeometry(QtCore.QRect(50, 130, 221, 20))
        self.edit_pacient.setReadOnly(True)
        self.edit_pacient.setObjectName("edit_pacient")
        self.edit_text = QtWidgets.QTextEdit(Edit_window)
        self.edit_text.setGeometry(QtCore.QRect(50, 200, 221, 101))
        self.edit_text.setObjectName("edit_text")
        self.edit_btn = QtWidgets.QPushButton(Edit_window)
        self.edit_btn.setGeometry(QtCore.QRect(130, 320, 75, 23))
        self.edit_btn.setObjectName("edit_btn")
        self.edit_label = QtWidgets.QLabel(Edit_window)
        self.edit_label.setGeometry(QtCore.QRect(120, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_label.setFont(font)
        self.edit_label.setObjectName("edit_label")
        self.edit_label_2 = QtWidgets.QLabel(Edit_window)
        self.edit_label_2.setGeometry(QtCore.QRect(120, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_label_2.setFont(font)
        self.edit_label_2.setObjectName("edit_label_2")
        self.edit_label_3 = QtWidgets.QLabel(Edit_window)
        self.edit_label_3.setGeometry(QtCore.QRect(100, 160, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_label_3.setFont(font)
        self.edit_label_3.setObjectName("edit_label_3")

        self.retranslateUi(Edit_window)
        QtCore.QMetaObject.connectSlotsByName(Edit_window)

    def retranslateUi(self, Edit_window):
        _translate = QtCore.QCoreApplication.translate
        Edit_window.setWindowTitle(_translate("Edit_window", "Edit note"))
        self.edit_btn.setText(_translate("Edit_window", "Обновить"))
        self.edit_label.setText(_translate("Edit_window", "Доктор"))
        self.edit_label_2.setText(_translate("Edit_window", "Пациент"))
        self.edit_label_3.setText(_translate("Edit_window", "Комментарий"))
