# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vipeg\Desktop\lol\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_window(object):
    def setupUi(self, Login_window):
        Login_window.setObjectName("Login_window")
        Login_window.resize(379, 348)
        self.login_btn = QtWidgets.QPushButton(Login_window)
        self.login_btn.setGeometry(QtCore.QRect(140, 290, 75, 23))
        self.login_btn.setObjectName("login_btn")
        self.login_username = QtWidgets.QLineEdit(Login_window)
        self.login_username.setGeometry(QtCore.QRect(30, 140, 311, 20))
        self.login_username.setInputMask("")
        self.login_username.setObjectName("login_username")
        self.login_password = QtWidgets.QLineEdit(Login_window)
        self.login_password.setGeometry(QtCore.QRect(30, 210, 311, 21))
        self.login_password.setInputMask("")
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password.setDragEnabled(False)
        self.login_password.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.login_password.setClearButtonEnabled(False)
        self.login_password.setObjectName("login_password")
        self.login_label = QtWidgets.QLabel(Login_window)
        self.login_label.setGeometry(QtCore.QRect(90, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.login_label_2 = QtWidgets.QLabel(Login_window)
        self.login_label_2.setGeometry(QtCore.QRect(90, 170, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.login_label_2.setFont(font)
        self.login_label_2.setObjectName("login_label_2")

        self.retranslateUi(Login_window)
        QtCore.QMetaObject.connectSlotsByName(Login_window)

    def retranslateUi(self, Login_window):
        _translate = QtCore.QCoreApplication.translate
        Login_window.setWindowTitle(_translate("Login_window", "Login"))
        self.login_btn.setText(_translate("Login_window", "Войти"))
        self.login_username.setPlaceholderText(_translate("Login_window", "Введите логин"))
        self.login_password.setPlaceholderText(_translate("Login_window", "Введите пароль"))
        self.login_label.setText(_translate("Login_window", "Введите логин"))
        self.login_label_2.setText(_translate("Login_window", "Введите пароль"))
