# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vipeg\Desktop\lol\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1307, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_table_note = QtWidgets.QTableWidget(self.centralwidget)
        self.main_table_note.setEnabled(True)
        self.main_table_note.setGeometry(QtCore.QRect(10, 170, 541, 651))
        self.main_table_note.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.main_table_note.setObjectName("main_table_note")
        self.main_table_note.setColumnCount(5)
        self.main_table_note.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_note.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_note.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_note.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_note.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_note.setHorizontalHeaderItem(4, item)
        self.main_btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.main_btn_quit.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.main_btn_quit.setObjectName("main_btn_quit")
        self.main_table_time = QtWidgets.QTableWidget(self.centralwidget)
        self.main_table_time.setGeometry(QtCore.QRect(640, 170, 651, 651))
        self.main_table_time.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.main_table_time.setObjectName("main_table_time")
        self.main_table_time.setColumnCount(6)
        self.main_table_time.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_time.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_time.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_time.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_time.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_time.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table_time.setHorizontalHeaderItem(5, item)
        self.main_btn_create = QtWidgets.QPushButton(self.centralwidget)
        self.main_btn_create.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.main_btn_create.setObjectName("main_btn_create")
        self.main_lable_name = QtWidgets.QLabel(self.centralwidget)
        self.main_lable_name.setGeometry(QtCore.QRect(10, 20, 461, 31))
        self.main_lable_name.setText("")
        self.main_lable_name.setObjectName("main_lable_name")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hospital"))
        item = self.main_table_note.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Доктор"))
        item = self.main_table_note.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Пациент"))
        item = self.main_table_note.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Комментарий"))
        item = self.main_table_note.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Изменить"))
        item = self.main_table_note.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Удалить"))
        self.main_btn_quit.setText(_translate("MainWindow", "Выйти"))
        item = self.main_table_time.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Доктор"))
        item = self.main_table_time.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Понедельник"))
        item = self.main_table_time.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Вторник"))
        item = self.main_table_time.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Среда"))
        item = self.main_table_time.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Четверг"))
        item = self.main_table_time.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Пятница"))
        self.main_btn_create.setText(_translate("MainWindow", "Создать запись"))
